#%RAML 1.0 Trait
  responses:
    400:
      description: Bad Request
    500:
      description: Internal Server Error

# Note: create a folder called Traits in that folder create file called commonResponses by selecting file type as trait
