#%RAML 1.0 SecurityScheme
type: x-client-id
description: Enforces client_id and client_secret
describedBy:
  headers:
    client_id:
      type: string
      required: true
    client_secret:
      type: string
      required: true
  responses:
    401:
      description: Unauthorized


#note: in design centre create folder(left most corner files +) called Security Scheme and in that respctive folder create file called securityScheme by selecting file type as Sceurity Scheme
